{"name": "Проверка ошибки при авторизации с неверным полем пароль", "status": "passed", "steps": [{"name": "Логин курьера в систему", "status": "passed", "parameters": [{"name": "data", "value": "{'login': ('darlene11', '#bmNoiDoA4'), 'password': '23432'}"}], "start": 1714855184181, "stop": 1714855184866}, {"name": "Проверка статуса и текста", "status": "passed", "parameters": [{"name": "code", "value": "404"}, {"name": "name", "value": "'message'"}, {"name": "text", "value": "'Учетная запись не найдена'"}], "start": 1714855184866, "stop": 1714855184866}], "start": 1714855184181, "stop": 1714855184868, "uuid": "01d42fda-b8a2-44f1-aa79-6083644ca5ff", "historyId": "e9ea1e117f42343546f328554a5f46be", "testCaseId": "e9ea1e117f42343546f328554a5f46be", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_auth_password_field_wrong", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Sasaraf"}, {"name": "thread", "value": "16480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}